name: Docker build'n'push

description: Builds image from repository and pushes image to Github Docker registry

inputs:
  image-name:
    description: 'Image name'
    required: true
  registry: # Use docker.io for Docker Hub if empty
    description: 'Docker registry'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Docker registry username'
    required: true
  password:
    description: 'Docker registry password'
    required: true

runs:
  using: 'composite'

  steps:
    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: type=ref,event=branch

    # Build and push Docker image
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true # Don't push on PR
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
